### ISSUE TITLE
Error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by devillom** [glad-tidings/DragonzLandBot-New#2]
Hi, i got error
![image](https://github.com/user-attachments/assets/73087847-ee48-4787-905e-4c905862343d)

**Comment by glad-tidings** [comment]
fix this issue
use new version (v2.3)

**Comment by devillom** [comment]
Nope, same problem. I'm  use session from vertus

**Comment by glad-tidings** [comment]
You can use the other my bot's sessions
![Screenshot 2024-12-20 144546](https://github.com/user-attachments/assets/613799b9-45ac-4171-a068-2dce72ea3218)

**Comment by glad-tidings** [comment]
[test.zip](https://github.com/user-attachments/files/18210138/test.zip)
Use this test bot and reply json result to me
You can change user detail but don't change game detail
